# Generated by Django 4.2.2 on 2023-06-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(db_index=True, default="any_name", max_length=200),
        ),
    ]
