# Generated by Django 4.2.2 on 2023-06-14 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_alter_product_name"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="order",
            table="shop_order",
        ),
    ]
